server:
  port: 8761
eureka:
  instance:
    hostname: 127.0.0.1
  server:
    eviction-interval-timer-in-ms: 5000  # 扫描失效服务的间隔时间（单位毫秒，默认是60*1000）即60秒
    enable-self-preservation: false #关闭eureka的自我保护，生产需要，防止网络连接导致的服务无法显示而默认显示持续1分钟
    wait-time-in-ms-when-sync-empty: 5 #设置 eureka server同步失败的等待时间 默认 5分 在这期间，它不向客户端提供服务注册信息
    number-of-replication-retries: 5   #设置 eureka server同步失败的重试次数 默认为 5 次
    renewal-percent-threshold: 0.49    #自我保护系数（默认0.85）
#    renewal-threshold-update-interval-ms:

